shares_latency_20_vs_1.csv: shares_latency_20_vs_1.sh
	./shares_latency_20_vs_1.sh shares_latency_20_vs_1.csv

shares_latency_all.csv: shares_latency_all.sh
	./shares_latency_all.sh shares_latency_all.csv

shares_latency_realistic.csv: shares_latency_realistic.sh
	./shares_latency_realistic.sh shares_latency_all.csv
